Add covariance test scripts
sampotter/butterfly pull request #5
Opened 2023-12-15 20:16 UTC by pbeckman

`examples/covariance/lbo_cov.c` contains an incomplete semi-translation from Julia of the Weyl's law error estimator...

I had to change quite a few small things (mostly in meson.build and in LAPACK and BLAS includes) to get things to compile on my homebrew environment on Mac, so this pull request is certainly meant to be cherry picked.

also, pulling the last three commits to `sampotter/butterfly/trunk` broke compilation on my machine, giving the following error:

```zsh
FAILED: libbutterfly.dylib 
/opt/homebrew/Cellar/gcc/13.2.0/bin/gcc-13  -o libbutterfly.dylib libbutterfly.dylib.p/src_array.c.o libbutterfly.dylib.p/src_bbox.c.o libbutterfly.dylib.p/src_bf.c.o libbutterfly.dylib.p/src_bessel.c.o libbutterfly.dylib.p/src_cheb.c.o libbutterfly.dylib.p/src_circle.c.o libbutterfly.dylib.p/src_disjoint_interval_list.c.o libbutterfly.dylib.p/src_dtype.c.o libbutterfly.dylib.p/src_ellipse.c.o libbutterfly.dylib.p/src_error.c.o libbutterfly.dylib.p/src_eval_tree.c.o libbutterfly.dylib.p/src_fac.c.o libbutterfly.dylib.p/src_fac_helm2.c.o libbutterfly.dylib.p/src_fac_span.c.o libbutterfly.dylib.p/src_fac_streamer.c.o libbutterfly.dylib.p/src_fiedler_tree.c.o libbutterfly.dylib.p/src_fiedler_tree_node.c.o libbutterfly.dylib.p/src_helm2.c.o libbutterfly.dylib.p/src_indexed_mat.c.o libbutterfly.dylib.p/src_interval.c.o libbutterfly.dylib.p/src_interval_tree.c.o libbutterfly.dylib.p/src_interval_tree_node.c.o libbutterfly.dylib.p/src_lbo.c.o libbutterfly.dylib.p/src_linalg.c.o libbutterfly.dylib.p/src_logging.c.o libbutterfly.dylib.p/src_lu.c.o libbutterfly.dylib.p/src_lu_csr_real.c.o libbutterfly.dylib.p/src_lu_dense_complex.c.o libbutterfly.dylib.p/src_mat.c.o libbutterfly.dylib.p/src_mat_block.c.o libbutterfly.dylib.p/src_mat_block_coo.c.o libbutterfly.dylib.p/src_mat_block_dense.c.o libbutterfly.dylib.p/src_mat_block_diag.c.o libbutterfly.dylib.p/src_mat_coo_complex.c.o libbutterfly.dylib.p/src_mat_coo_real.c.o libbutterfly.dylib.p/src_mat_csr_real.c.o libbutterfly.dylib.p/src_mat_csr_real.umfpack.c.o libbutterfly.dylib.p/src_mat_dense.c.o libbutterfly.dylib.p/src_mat_dense_complex.c.o libbutterfly.dylib.p/src_mat_dense_real.c.o libbutterfly.dylib.p/src_mat_diag_real.c.o libbutterfly.dylib.p/src_mat_diff.c.o libbutterfly.dylib.p/src_mat_func.c.o libbutterfly.dylib.p/src_mat_givens.c.o libbutterfly.dylib.p/src_mat_identity.c.o libbutterfly.dylib.p/src_mat_perm.c.o libbutterfly.dylib.p/src_mat_product.c.o libbutterfly.dylib.p/src_mat_sum.c.o libbutterfly.dylib.p/src_mat_zero.c.o libbutterfly.dylib.p/src_mem.c.o libbutterfly.dylib.p/src_node_array.c.o libbutterfly.dylib.p/src_node_span.c.o libbutterfly.dylib.p/src_octree.c.o libbutterfly.dylib.p/src_octree.get_nearest_neighbors.c.o libbutterfly.dylib.p/src_octree_node.c.o libbutterfly.dylib.p/src_perm.c.o libbutterfly.dylib.p/src_points.c.o libbutterfly.dylib.p/src_poisson_disk_sampling.c.o libbutterfly.dylib.p/src_ptr_array.c.o libbutterfly.dylib.p/src_quadrature.c.o libbutterfly.dylib.p/src_quadtree.c.o libbutterfly.dylib.p/src_quadtree_node.c.o libbutterfly.dylib.p/src_rand.c.o libbutterfly.dylib.p/src_real_array.c.o libbutterfly.dylib.p/src_size_array.c.o libbutterfly.dylib.p/src_splitmix64.c.o libbutterfly.dylib.p/src_timer.c.o libbutterfly.dylib.p/src_tree.c.o libbutterfly.dylib.p/src_tree_iter.c.o libbutterfly.dylib.p/src_tree_iter_post_order.c.o libbutterfly.dylib.p/src_tree_level_iter.c.o libbutterfly.dylib.p/src_tree_node.c.o libbutterfly.dylib.p/src_trimesh.c.o libbutterfly.dylib.p/src_trimesh.get_level_set_submesh.c.o libbutterfly.dylib.p/src_types.c.o libbutterfly.dylib.p/src_util.c.o libbutterfly.dylib.p/src_vec.c.o libbutterfly.dylib.p/src_vec_complex.c.o libbutterfly.dylib.p/src_vec_real.c.o libbutterfly.dylib.p/src_vec_zero.c.o libbutterfly.dylib.p/src_vectors.c.o libbutterfly.dylib.p/src_xoshiro256plus.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -shared -install_name @rpath/libbutterfly.dylib -Wl,-rpath,/opt/homebrew/Cellar/arpack/3.9.1/libexec/lib -Wl,-rpath,/opt/homebrew/Cellar/gsl/2.7.1/lib -lopenblas -lgfortran -lm /opt/homebrew/Cellar/arpack/3.9.1/libexec/lib/libarpack.dylib /opt/homebrew/Cellar/gsl/2.7.1/lib/libgsl.dylib /opt/homebrew/Cellar/gsl/2.7.1/lib/libgslcblas.dylib -lumfpack
Undefined symbols for architecture arm64:
  "_bfTrimeshGetVisibility", referenced from:
      _bfMatCsrRealNewViewFactorMatrixFromTrimesh in src_mat_csr_real.c.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
```

2023-12-16 19:25 UTC, sampotter requested changes

2023-12-16 19:25 UTC, sampotter commented on meson.build
> +  '/opt/homebrew/lib/python3.12/site-packages/numpy/core/include'
I tried looking into what the deal with Meson and Homebrew is on Apple Silicon, and it seems scary. My hunch is that there is a simple way of fixing the problems you're having by setting `CFLAGS` and `LIBRARY_PATH` before invoking `meson setup ...` initially, but I don't have a Mac so it's hard for me to try stuff out.

This issue *might* be related: https://github.com/mesonbuild/meson/pull/12170.

Morally, we don't want to hardcode paths like this here (as you know). For now, I would just back these changes off from the PR and keep them as unstaged local changes in your repo.

If you do find a way to get this to work reliably on Mac that doesn't involve mangling the build file, please add a note about it in the README and submit a PR. I will greatly appreciate it.

2023-12-16 19:25 UTC, sampotter commented on examples/covariance/lbo_cov.c
> +#include <time.h>
Use `BfTimer` from `bf/timer.h` instead of using `time.h` directly. 

Usage is:
```
BfTimer timer;
bfTimerReset(&timer); // maybe unnecessary the first time, can't remember
... // do something that takes a while
BfReal t0 = bfTimerGetElapsedTimeInSeconds(&timer); // measure time since call to reset
... // do some more stuff
BfReal t1 = bfTimerGetElapsedTimeInSeconds(&timer); 
// now t1 - t0 is time between two timer calls
bfTimerReset(&timer); // start over...
```
This just calls through and should do what you're doing already (IIRC) but is less gross.

2023-12-16 19:25 UTC, sampotter commented on examples/covariance/lbo_cov.c
> +  // bfTreeDelete(&rowTree); // This segfaults...
Segfault unsurprising here. Will fix later. Only downstream consequence of not cleaning up here is that the OS will do it when the program exits.

2023-12-16 19:25 UTC, sampotter commented on meson.build
> +blas_dep = cc.find_library('openblas', required : true)
```
if host_machine.system() == 'linux'
  blas_dep = dependency('flexiblas', required : true)
  lapacke_dep = dependency('lapacke', required : true)
elif host_machine.system() == 'darwin'
  blas_dep = cc.find_library('openblas', required : true)
elif host_machine.system() == 'windows'
  error('Windows unsupported currently')
endif
```

2023-12-16 19:25 UTC, sampotter commented on meson.build
> -  lapacke_dep,
Remove `blas_dep` and `lapacke_dep` from `butterfly_dependencies`. Then, after `butterfly_dependencies` is defined, add:
```
if host_machine.system() == 'linux'
  butterfly_dependencies += [blas_dep, lapacke_dep]
elif host_machine.system() == 'darwin'
  butterfly_dependencies += [blas_dep]
elif host_machine.system() == 'windows'
  error('Windows unsupported currently')
endif
```

2023-12-16 19:25 UTC, sampotter commented on src/lu_csr_real.c
> +#include <umfpack.h>
```
#if defined BF_LINUX
#  include <suitesparse/umfpack.h>
#elif defined BF_DARWIN
#  include <umfpack.h>
#else
#  error "Unknown platform"
#endif
```

2023-12-16 19:25 UTC, sampotter commented on src/mat_csr_real.umfpack.c
> +#include <umfpack.h>
```
#if defined BF_LINUX
#  include <suitesparse/umfpack.h>
#elif defined BF_DARWIN
#  include <umfpack.h>
#else
#  error "Unknown platform"
#endif
```

2023-12-16 19:25 UTC, sampotter commented on src/mat_dense_complex.c
> +#include <lapacke.h>
Try just removing this line? Looks like LAPACK should get pulled in when `bf/blas.h` in included.

2023-12-16 19:25 UTC, sampotter commented on src/mat_dense_real.c
> +#include <lapacke.h>
Ditto.

2023-12-16 19:25 UTC, sampotter commented on examples/covariance/lbo_cov.c
> +    err_est = norm(gamma_(lam_est[1+r:end]).^2) / norm(gamma_(ls).^2);
Something like this:
```
// Don't try to extrapolate if we don't have enough frequencies:
if (freqs->size <= r)
  continue;

BfReal numer = 0;
BfReal denom = 0;
for (BfSize i = 0; i < freqs->size; ++i) {
  BfReal lam = pow(bfVecRealGetElt(freqs, i), 2);
  numer += i*lam;
  denom += i*i;
}
BfReal m = numer/denom;

numer = 0;
denom = 0;
for (BfSize i = r; r < freqs->size; ++r) {
  numer += pow(tgamma(m*i), 2);
  denom += // TODO: what is "ls"...? couldn't find it...
}
BfReal err_es = sqrt(numer)/sqrt(denom);
```

2023-12-17 02:31 UTC, pbeckman commented on meson.build
> +  '/opt/homebrew/lib/python3.12/site-packages/numpy/core/include'
I found that meson accepts a `-Dc_args` flag, and including these directories there did the trick!

2023-12-17 15:22 UTC, pbeckman commented
I also added an ```#ifdef BF_EMBREE``` into `src/mat_csr_real.c` to fix the linker error.

2023-12-18 00:36 UTC, sampotter commented
This all looks good to me. Can you just add a quick note somewhere in the README explaining how to use c_args to get this to compile on "Mac + Homebrew"? Then I will merge.

2023-12-18 16:59 UTC, merged